
export
--table
st_app_pv
--connect
jdbc:oracle:thin:@10.60.60.30:1521:rptods
--username
rptods
--password
a9IkEr2NS00$l$QW
--input-fields-terminated-by
'\001'
--input-lines-terminated-by
'\n'
--export-dir
/user/hive/warehouse/st_app_pv
--columns
ts,cust_no,hbone_no,pageid,htag
--input-null-string
\\N
--input-null-non-string
\\N
